version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: patrimonio-postgres
    environment:
      POSTGRES_DB: patrimonio_db
      POSTGRES_USER: patrimonio_user
      POSTGRES_PASSWORD: patrimonio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - patrimonio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patrimonio_user -d patrimonio_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicação Spring Boot
  app:
    build: .
    container_name: patrimonio-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patrimonio_db
      SPRING_DATASOURCE_USERNAME: patrimonio_user
      SPRING_DATASOURCE_PASSWORD: patrimonio_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      JAVA_OPTS: "-Xmx1g -Xms512m"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - patrimonio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: patrimonio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - patrimonio-network
    restart: unless-stopped

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: patrimonio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - patrimonio-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  patrimonio-network:
    driver: bridge

