spring:
  application:
    name: sistema-patrimonio-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/patrimonio_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  cache:
    type: none
  
  data:
    redis:
      enabled: false
  
  mail:
    enabled: false
  
  quartz:
    enabled: false

# Server Configuration
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Security Configuration
security:
  jwt:
    secret: your-secret-key-here-make-it-very-long-and-secure-in-production
    expiration: 86400000 # 24 hours

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    redis:
      enabled: false
    db:
      enabled: true

# Logging Configuration
logging:
  level:
    com.manus.patrimonio: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
